### ISSUE TITLE
Potential garbage value used in 'utf8.c'

### ISSUE THREAD

**Issue by zv-io** [rain-1/linenoise#29]
The function `utf8BytesToCodePoint()` in `utf8.c` is not guaranteed to set the memory pointed to by parameter `int *cp`, which means that this (circa line 458):

```
    int cp;
    utf8BytesToCodePoint(buf + pos, len, &cp);
    if (!isCombiningChar(cp)) {
        if (col_len != NULL) *col_len = isWideChar(cp) ? 2 : 1;
        return end - pos;
    }
```
May end up using garbage.

**Comment by rain-1** [comment]
https://github.com/rain-1/linenoise/commit/1e6ffd4e32c435149878cbffa815670f9f9afd24
